config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path("", RedirectView.as_view(pattern_name = "news:topic_feed", permanent = False), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("news_website.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # re_path(r'^news/', include('news_website.news.urls')),
    path("", include('news_website.news.urls')),
    path("corpann/", include('news_website.corporate_announcements.urls')),
    path("experiments/", include("news_website.experiments.urls", namespace="experiments")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

news_website/corporate_announcements/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "corporate_announcements"

urlpatterns = [
    re_path(
        route=r'^announcements/all/$',
        view=views.corporate_announcements,
        name='corporate_announcements',
    ),
    re_path(
        route=r'^announcements/home/$',
        view=views.home_announcements,
        name='home_announcements',
    ),
    re_path(
        route=r'^announcements/discover/$',
        view=views.discover_announcements,
        name='discover_announcements',
    ),
    re_path(
        route=r'^api/fetch/announcements/$',
        view=views.fetch_announcements,
        name='fetch_announcements_from_server',
    ),

    re_path(
        route=r'^api/company/following/$',
        view=views.following_companies,
        name='following_companies',
    ),
    re_path(
        route=r'^api/fetchForOldUser/$',
        view=views.fetch_announcements_for_old_user,
        name='fetch_announcements',
    ),
    re_path(
        route=r'^api/autocomplete/$',
        view=views.autocomplete,
        name='autocomplete',
    ),
    re_path(
        route=r'^api/follow/$',
        view=views.follow_company,
        name='follow_company',
    ),
    re_path(
        route=r'^api/unfollow/$',
        view=views.unfollow_company,
        name='unfollow_company',
    ),
    # re_path(
    #     route=r'^api/fetch/announcements/$',
    #     view=views.fetch_announcements_from_server,
    #     name='fetch_announcements_from_server',
    # ),
]

news_website/experiments/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "experiments"

urlpatterns = [
    re_path(
        route=r'^news/query/$',
        view=views.get_everything_by_query,
        name='get_everything_by_query',
    ),
    re_path(
        route=r'^news/feed/$',
        view=views.topic_feed,
        name='topic_feed', # HomePage
    ),
    re_path(
        route=r'^news/test/',
        view=views.test,
        name='test',
    ),
]

news_website/news/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "news"

urlpatterns = [
    re_path(
        route=r'^$',
        view=views.topic_feed,
        name='home',
    ),
    path(
        'follow/<topicname>/',
        view=views.get_topic_by_query,
        name='get_topic_by_query',
    ),
    re_path(
        route=r'^analytics/admin/$',
        view=views.analytics_page,
        name='analytics_page',
    ),
    # re_path(
    #     route=r'^news/$',
    #     view=views.topic_feed,
    #     name='search_page',
    # ),
    re_path(
        route=r'^news/sources/$',
        view=views.get_all_sources,
        name='get_all_sources',
    ),
    re_path(
        route=r'^news/discovery/$',
        view=views.discovery_page,
        name='discovery_page',
    ),

    re_path(
        route=r'^news/discovery/follow/$',
        view=views.follow_topic,
        name='follow_topic',
    ),
    re_path(
        route=r'^news/discovery/(?P<item>[\w-]+)/$',
        view=views.discover_each_item,
        name='discover_each_item',
    ),

    re_path(
        route=r'^news/top/$',
        view=views.TopHeadlinesListView.as_view(),
        name='top_headlines',
    ),
    re_path(
        route=r'^news/query/$',
        view=views.get_everything_by_query,
        name='get_everything_by_query',
    ),
    re_path(
        route=r'^news/add/$',
        view=views.landing_page,
        name='landing_page',
    ),
    re_path(
        route=r'^news/feed/$',
        view=views.topic_feed,
        name='topic_feed', # HomePage
    ),
    re_path(
        route=r'^news/unfollow/$',
        view=views.unfollow_topic,
        name='unfollow_topic',
    ),
    re_path(
        route=r'^concalls/$',
        view=views.concalls_view,
        name='concalls_view',
    ),
    re_path(
        route=r'^trending/$',
        view=views.trending_view,
        name='trending_view',
    ),
    re_path(
        route=r'^news/autocomplete/$',
        view=views.autocomplete_home_page_text,
        name='autocomplete_home_page_text',
    ),
    # re_path(
    #     route=r'^query/(?P<query>\w+)/$',
    #     view=views.get_everything_by_query,
    #     name='get_everything_by_query',
    # ),
    re_path(
        route=r'^news/test/',
        view=views.test,
        name='test',
    ),
    
    ###############
    # Blogs

    re_path(
        route=r'^blogs/news/page/$',
        view=views.blogs_news_page,
        name='blogs_news_page',
    ),

    re_path(
        route=r'^blogs/news/page/test',
        view=views.blogs_test,
        name='blogs_test',
    ),
    
    re_path(
        route=r'^api/blogs/topics/follow',
        view=views.blogs_follow_topic,
        name='blogs_follow_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/unfollow',
        view=views.blogs_unfollow_topic,
        name='blogs_unfollow_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/autocomplete',
        view=views.blogs_autocomplete_topic,
        name='blogs_autocomplete_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/getAllFollowing/',
        view=views.blogs_get_all_user_following_topics,
        name='blogs_get_all_user_following_topics',
    ),
    re_path(
        route=r'^api/blogs/news/feed/',
        view=views.blogs_fetch_news_articles,
        name='blogs_fetch_news_articles',
    ),
]

news_website/users/urls.py
from django.urls import path

from news_website.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:email>/", view=user_detail_view, name="detail"),
]

news_website/corporate_announcements/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Corpann_Company(models.Model):
    company_name = models.CharField(max_length=100, unique=True)
    company_scrip_id = models.IntegerField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.company_name


class User_Companies(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    company = models.ForeignKey(Corpann_Company, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'company']
        verbose_name_plural = _('Users_Companies')

    def __str__(self):
        return self.user.email + ' : ' + self.company.company_name

news_website/experiments/models.py
from django.db import models

# Create your models here.

news_website/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password1'].widget.attrs.update({'placeholder':_('Password')})
    
    error_message = admin_forms.UserCreationForm.error_messages.update(
                {"duplicate_email": _("This email has already been taken.")}
            )
    password2 = None

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ('name','email')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.EmailInput(
                attrs={'placeholder': 'E-mail'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email

        raise ValidationError(self.error_messages["duplicate_email"])

news_website/corporate_announcements/views.py
from django.contrib.auth import login
from django.shortcuts import render
from django.http import JsonResponse, response
from django.contrib.auth.decorators import login_required
from .models import Corpann_Company, User_Companies

import requests
import json

import logging

logger = logging.getLogger(__name__)

ANNOUNCEMENTS_RANGE_START = 0
ANNOUNCEMENTS_RANGE_END = 20

# Create your views here.

def autocomplete(request):
    substr = request.GET.get('search')
    data = []
    companies = Corpann_Company.objects.filter(company_name__iregex = rf'(.*){substr}(.*)').values("company_name","company_scrip_id")
    data.extend(companies)
    # data = list(set(data))
    ret = {"data" : []}
    for v in data:
        ret['data'].append({"company_name":v['company_name'].upper(), "scrip_id":v['company_scrip_id']})
    return JsonResponse(ret)


@login_required
def home_announcements(request):
    return render(request,'corporate_announcements/announcements_home.html',{})

@login_required
def corporate_announcements(request):
    return render(request,'corporate_announcements/announcements.html',{})


@login_required
def discover_announcements(request):
    return render(request,'corporate_announcements/announcements_discover.html',{})

@login_required
def fetch_announcements_for_old_user(request):
    URL = 'http://165.22.209.84/refresh_feed'
    params = {'email': request.user.email}
    api_response = requests.get(URL, params=params)
    if api_response.status_code!=200:
        return JsonResponse({'data':[]})
    
    json_data = {'data':api_response.json()['data']}

    return JsonResponse(json_data)


@login_required
def following_companies(request):
    following_companies = list(set(User_Companies.objects.filter(user=request.user).values_list('company__company_name','company__company_scrip_id')))
    ret = {"data" : []}
    for comp_data in following_companies:
        ret["data"].append({"company_name":comp_data[0],"scrip_id":comp_data[1]})

    return JsonResponse(ret)


@login_required
def follow_company(request):
    res = {"data":{
        "company_status" : "UnConfirmed",
        "scrip_id" : -1
    }}
    if request.method == "GET":
        company_scrip_id = request.GET.get("company")
        try:
            company = Corpann_Company.objects.get(company_scrip_id=int(company_scrip_id))
            try:
                user_companies_obj, is_created = User_Companies.objects.get_or_create(user=request.user, company=company)
                res = {"data" : {
                    "company_status" : "Confirmed",
                    "scrip_id" : company.company_scrip_id
                }}
                return JsonResponse(res)
            except:
                return JsonResponse(res)
        except:
            return JsonResponse(res)
    return JsonResponse(res)

@login_required
def unfollow_company(request):
    res = {"data":{
        "company_status" : "UnConfirmed",
        "scrip_id" : -1
    }}
    if request.method == "GET":
        company_scrip_id = request.GET.get("company")
        try:
            company = Corpann_Company.objects.get(company_scrip_id=int(company_scrip_id))
            try:
                user_companies_obj = User_Companies.objects.get(user=request.user, company=company)
                user_companies_obj.delete()
                res = {"data" : {
                    "company_status" : "Confirmed",
                    "scrip_id" : company.company_scrip_id
                }}
                return JsonResponse(res)
            except:
                return JsonResponse(res)
        except:
            return JsonResponse(res)
    return JsonResponse(res)

@login_required
def fetch_announcements(request):
    companies_followed_by_user = User_Companies.objects.filter(user=request.user).values_list('company__company_scrip_id',flat=True)
    range_begin = ANNOUNCEMENTS_RANGE_START
    range_end = ANNOUNCEMENTS_RANGE_END

    URL = 'http://165.22.209.84/corpann/get_announcements/'
    params = {'companies': companies_followed_by_user,'rangeBegin':ANNOUNCEMENTS_RANGE_START,
    'rangeEnd': ANNOUNCEMENTS_RANGE_END}
    response = requests.get(URL, params=params)
    json_data = {'data':response.json()['data']}
    return JsonResponse(json_data)

news_website/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

news_website/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    # slug_field = "username"
    slug_field = "email"
    # slug_url_kwarg = "username"
    slug_url_kwarg = "email"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["email"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"email": self.request.user.email})

    def get_object(self):
        return User.objects.get(email=self.request.user.email)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False
    pattern_name = "news:topic_feed"

    # def get_redirect_url(self):
    #     return reverse("users:detail", kwargs={"email": self.request.user.email})


user_redirect_view = UserRedirectView.as_view()

news_website/templates/bootstrap-skeleton.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-GLGL5J53BG"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-GLGL5J53BG');
        </script>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121464669-2"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-121464669-2');
        </script>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Keepup Live{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block head_tags %}
        
        {% endblock head_tags %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

        {% block staticfiles %}
        {% endblock staticfiles %}

        {% block stylesheet %}
        {% endblock stylesheet %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% if not redirect_url %}
        <div id="top-navbar" class="container mx-auto">
          <nav class="navbar navbar-expand-lg navbar-light bg-white">
              {% comment %} <a class="navbar-brand" href="#">Keepup Live</a> {% endcomment %}
              <div class="">
                <a class="navbar-brand" href="{% url 'news:topic_feed' %}">
                  <img class="img-fluid" src="{% static 'images/accounts/keepup_logo.jpg' %}" alt="Logo" style="height:60px;" />
                </a>
              </div>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                  {% comment %} <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                  </li> {% endcomment %}
                  {% if request.user.is_authenticated %}
                  <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'news:discovery_page' %}">Discover</a>
                  </li>
                  <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'news:landing_page' %}">Following</a>
                  </li>
                  {% comment %} <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'corporate_announcements:home_announcements' %}">My Announcements</a>
                  </li> {% endcomment %}
                  {% comment %} <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'corporate_announcements:corporate_announcements' %}">My Announcements</a>
                  </li>
                  <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'corporate_announcements:discover_announcements' %}">Discover Announcements</a>
                  </li> {% endcomment %}
                  <li class="nav-item d-flex justify-content-end">
                      <a class="nav-link font-weight-bold" href="{% url 'account_logout' %}">Logout</a>
                  </li>
                  {% endif %}
                  {% comment %} <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Dropdown link
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                  </li> {% endcomment %}
                  </ul>
              </div>
          </nav>
        </div>
        {% endif %}
        {% block body_content %}

        {% endblock body_content %}
        {% comment %} <script src="" async defer></script> {% endcomment %}
        <!-- JS, Popper.js, and jQuery -->

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        
        
        
        {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js" integrity="sha512-ZKNVEa7gi0Dz4Rq9jXcySgcPiK+5f01CqW+ZoKLLKr9VMXuCsw3RjWiv8ZpIOa0hxO79np7Ec8DDWALM0bDOaQ==" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.min.js" integrity="sha512-m3kH21aSkKrGeoqdb7IP7rlu1VcQee5VrjLQepeSOp5M05Wl6HwqJ1Jwo14EHOuBg77pkAlBtQuVMPVeXzfueg==" crossorigin="anonymous"></script> {% endcomment %}

        {% block js_includes %}
        
        {% endblock js_includes %}
    </body>
</html>