config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path("", RedirectView.as_view(pattern_name = "news:topic_feed", permanent = False), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("news_website.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # re_path(r'^news/', include('news_website.news.urls')),
    path("", include('news_website.news.urls')),
    path("corpann/", include('news_website.corporate_announcements.urls')),
    path("experiments/", include("news_website.experiments.urls", namespace="experiments")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

news_website/experiments/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "experiments"

urlpatterns = [
    re_path(
        route=r'^news/query/$',
        view=views.get_everything_by_query,
        name='get_everything_by_query',
    ),
    re_path(
        route=r'^news/feed/$',
        view=views.topic_feed,
        name='topic_feed', # HomePage
    ),
    re_path(
        route=r'^news/test/',
        view=views.test,
        name='test',
    ),
]

news_website/news/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "news"

urlpatterns = [
    re_path(
        route=r'^$',
        view=views.topic_feed,
        name='home',
    ),
    path(
        'follow/<topicname>/',
        view=views.get_topic_by_query,
        name='get_topic_by_query',
    ),
    re_path(
        route=r'^analytics/admin/$',
        view=views.analytics_page,
        name='analytics_page',
    ),
    # re_path(
    #     route=r'^news/$',
    #     view=views.topic_feed,
    #     name='search_page',
    # ),
    re_path(
        route=r'^news/sources/$',
        view=views.get_all_sources,
        name='get_all_sources',
    ),
    re_path(
        route=r'^news/discovery/$',
        view=views.discovery_page,
        name='discovery_page',
    ),

    re_path(
        route=r'^news/discovery/follow/$',
        view=views.follow_topic,
        name='follow_topic',
    ),
    re_path(
        route=r'^news/discovery/(?P<item>[\w-]+)/$',
        view=views.discover_each_item,
        name='discover_each_item',
    ),

    re_path(
        route=r'^news/top/$',
        view=views.TopHeadlinesListView.as_view(),
        name='top_headlines',
    ),
    re_path(
        route=r'^news/query/$',
        view=views.get_everything_by_query,
        name='get_everything_by_query',
    ),
    re_path(
        route=r'^news/add/$',
        view=views.landing_page,
        name='landing_page',
    ),
    re_path(
        route=r'^news/feed/$',
        view=views.topic_feed,
        name='topic_feed', # HomePage
    ),
    re_path(
        route=r'^news/unfollow/$',
        view=views.unfollow_topic,
        name='unfollow_topic',
    ),
    re_path(
        route=r'^concalls/$',
        view=views.concalls_view,
        name='concalls_view',
    ),
    re_path(
        route=r'^trending/$',
        view=views.trending_view,
        name='trending_view',
    ),
    re_path(
        route=r'^news/autocomplete/$',
        view=views.autocomplete_home_page_text,
        name='autocomplete_home_page_text',
    ),
    # re_path(
    #     route=r'^query/(?P<query>\w+)/$',
    #     view=views.get_everything_by_query,
    #     name='get_everything_by_query',
    # ),
    re_path(
        route=r'^news/test/',
        view=views.test,
        name='test',
    ),
    
    ###############
    # Blogs

    re_path(
        route=r'^blogs/news/page/$',
        view=views.blogs_news_page,
        name='blogs_news_page',
    ),

    re_path(
        route=r'^blogs/news/page/test',
        view=views.blogs_test,
        name='blogs_test',
    ),
    
    re_path(
        route=r'^api/blogs/topics/follow',
        view=views.blogs_follow_topic,
        name='blogs_follow_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/unfollow',
        view=views.blogs_unfollow_topic,
        name='blogs_unfollow_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/autocomplete',
        view=views.blogs_autocomplete_topic,
        name='blogs_autocomplete_topic',
    ),

    re_path(
        route=r'^api/blogs/topics/getAllFollowing/',
        view=views.blogs_get_all_user_following_topics,
        name='blogs_get_all_user_following_topics',
    ),
    re_path(
        route=r'^api/blogs/news/feed/',
        view=views.blogs_fetch_news_articles,
        name='blogs_fetch_news_articles',
    ),
]

news_website/users/urls.py
from django.urls import path

from news_website.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:email>/", view=user_detail_view, name="detail"),
]

news_website/corporate_announcements/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Corpann_Company(models.Model):
    company_name = models.CharField(max_length=100, unique=True)
    company_scrip_id = models.IntegerField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.company_name


class User_Companies(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    company = models.ForeignKey(Corpann_Company, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'company']
        verbose_name_plural = _('Users_Companies')

    def __str__(self):
        return self.user.email + ' : ' + self.company.company_name

news_website/experiments/models.py
from django.db import models

# Create your models here.

news_website/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password1'].widget.attrs.update({'placeholder':_('Password')})
    
    error_message = admin_forms.UserCreationForm.error_messages.update(
                {"duplicate_email": _("This email has already been taken.")}
            )
    password2 = None

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ('name','email')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.EmailInput(
                attrs={'placeholder': 'E-mail'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email

        raise ValidationError(self.error_messages["duplicate_email"])

news_website/corporate_announcements/views.py
from django.contrib.auth import login
from django.shortcuts import render
from django.http import JsonResponse, response
from django.contrib.auth.decorators import login_required
from .models import Corpann_Company, User_Companies

import requests
import json

import logging

logger = logging.getLogger(__name__)

ANNOUNCEMENTS_RANGE_START = 0
ANNOUNCEMENTS_RANGE_END = 20

# Create your views here.

def autocomplete(request):
    substr = request.GET.get('search')
    data = []
    companies = Corpann_Company.objects.filter(company_name__iregex = rf'(.*){substr}(.*)').values("company_name","company_scrip_id")
    data.extend(companies)
    # data = list(set(data))
    ret = {"data" : []}
    for v in data:
        ret['data'].append({"company_name":v['company_name'].upper(), "scrip_id":v['company_scrip_id']})
    return JsonResponse(ret)


@login_required
def home_announcements(request):
    return render(request,'corporate_announcements/announcements_home.html',{})

@login_required
def corporate_announcements(request):
    return render(request,'corporate_announcements/announcements.html',{})


@login_required
def discover_announcements(request):
    return render(request,'corporate_announcements/announcements_discover.html',{})

@login_required
def fetch_announcements_for_old_user(request):
    URL = 'http://165.22.209.84/refresh_feed'
    params = {'email': request.user.email}
    api_response = requests.get(URL, params=params)
    if api_response.status_code!=200:
        return JsonResponse({'data':[]})
    
    json_data = {'data':api_response.json()['data']}

    return JsonResponse(json_data)


@login_required
def following_companies(request):
    following_companies = list(set(User_Companies.objects.filter(user=request.user).values_list('company__company_name','company__company_scrip_id')))
    ret = {"data" : []}
    for comp_data in following_companies:
        ret["data"].append({"company_name":comp_data[0],"scrip_id":comp_data[1]})

    return JsonResponse(ret)


@login_required
def follow_company(request):
    res = {"data":{
        "company_status" : "UnConfirmed",
        "scrip_id" : -1
    }}
    if request.method == "GET":
        company_scrip_id = request.GET.get("company")
        try:
            company = Corpann_Company.objects.get(company_scrip_id=int(company_scrip_id))
            try:
                user_companies_obj, is_created = User_Companies.objects.get_or_create(user=request.user, company=company)
                res = {"data" : {
                    "company_status" : "Confirmed",
                    "scrip_id" : company.company_scrip_id
                }}
                return JsonResponse(res)
            except:
                return JsonResponse(res)
        except:
            return JsonResponse(res)
    return JsonResponse(res)

@login_required
def unfollow_company(request):
    res = {"data":{
        "company_status" : "UnConfirmed",
        "scrip_id" : -1
    }}
    if request.method == "GET":
        company_scrip_id = request.GET.get("company")
        try:
            company = Corpann_Company.objects.get(company_scrip_id=int(company_scrip_id))
            try:
                user_companies_obj = User_Companies.objects.get(user=request.user, company=company)
                user_companies_obj.delete()
                res = {"data" : {
                    "company_status" : "Confirmed",
                    "scrip_id" : company.company_scrip_id
                }}
                return JsonResponse(res)
            except:
                return JsonResponse(res)
        except:
            return JsonResponse(res)
    return JsonResponse(res)

@login_required
def fetch_announcements(request):
    companies_followed_by_user = User_Companies.objects.filter(user=request.user).values_list('company__company_scrip_id',flat=True)
    range_begin = ANNOUNCEMENTS_RANGE_START
    range_end = ANNOUNCEMENTS_RANGE_END

    URL = 'http://165.22.209.84/corpann/get_announcements/'
    params = {'companies': companies_followed_by_user,'rangeBegin':ANNOUNCEMENTS_RANGE_START,
    'rangeEnd': ANNOUNCEMENTS_RANGE_END}
    response = requests.get(URL, params=params)
    json_data = {'data':response.json()['data']}
    return JsonResponse(json_data)

news_website/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

news_website/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    # slug_field = "username"
    slug_field = "email"
    # slug_url_kwarg = "username"
    slug_url_kwarg = "email"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["email"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"email": self.request.user.email})

    def get_object(self):
        return User.objects.get(email=self.request.user.email)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False
    pattern_name = "news:topic_feed"

    # def get_redirect_url(self):
    #     return reverse("users:detail", kwargs={"email": self.request.user.email})


user_redirect_view = UserRedirectView.as_view()

news_website/templates/experiments/news_home.html
{% include 'bootstrap-skeleton.html' %}

{% load news_home %}

{% load static %}

{% block staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news/news_home.css' %}" />
{% endblock staticfiles %}

{% block content_body %}

{% if redirect_url %}
<div class="container d-flex justify-content-center" id="loading" style="height: 100vh;width: 100%;">
  <div class="d-flex align-self-center">
    <img class="rotate-infinite"  id="loading-image" src="{% static 'images/news/keepup_crop.jpg' %}" alt="Loading..." />
  </div>
  
</div>

<div id="success">

{% else %}

<div class="container mx-auto">
  <!-- <div class="row">
    <div class="col">
      <a href="{% url 'account_logout' %}">   
        <button href="" class="btn btn-light z-depth-0 float-right border text-primary my-3">
          Logout</button>
      </a>
    </div>
  </div> -->
  <div class="row pb-2 px-3">
    {% comment %} <div class="col-sm-12 col-md-2 d-flex justify-content-center">
      <a href="{% url 'news:topic_feed' %}">
        <img class="img-fluid" src="{% static 'images/accounts/keepup_logo.jpg' %}" alt="Logo" style="height: 50px;" />
      </a>
    </div> {% endcomment %}
    <div class="col-sm-12 col-md-12">
      <form class="input-group mb-3" action="{% url 'experiments:get_everything_by_query' %}" method="get">
        {% csrf_token %}
        <input type="search" class="form-control" placeholder="Search companies, sectors or topics" aria-label="Search Companies"
                id="dv-autocomplete"  name="query" aria-describedby="basic-addon2" required> 
        <div class="input-group-append">
          <button class="btn btn-primary px-1" type="submit">Search</button>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-10 mx-auto">

      {% for topic in topics  %}
      <div class="row py-3 shadow-sm">
        <div class="col-7 col-md-4">
          <p class="pt-3 text-secondary text-break font-weight-bold align-middle text-uppercase">
          {{ topic.name }}
          </p>
        </div>
        <div class="col-2 col-md-2 align-self-center">
          <form action="{% url 'news:topic_feed' %}" method="post">
          {% csrf_token %}
            {% comment %} <input type="text" name="topic" value="{{ user_topic.topic.name }}" class="form-control d-none"> {% endcomment %}
            <input type="" class="form-control d-none" aria-label=""
                              name="query" value="{{ topic.name }}" >
            <div class="input-group-append">
              <button class=" btn btn-success mt-2" type="submit">Follow</button>
            </div>
          </form>
        </div>
      </div>
      {% endfor %}

      {% for message in messages  %}
      <div class="row py-1">
        <div class="col ">
          <p class="pt-3 text-secondary font-weight-bold align-middle">
          {{ message }}
          </p>
        </div>
      </div>
      {% endfor %}


      {% if articles_list %}
      {% for article in articles_list %}
        <div class="row">
          <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-md-9 col-sm-push-3">
                <div class="card-body">
                  <a target="__blank" href="{{ article.url }}" class="">
                    <h5 class="card-title font-weight-bold  ">{{ article.title }}</h5>
                  </a>
                  {% comment %} <!-- <p class="card-text d-inline">Article by : {{ article.author }}</p> -->
                  <!-- <p class="card-text d-inline"><small class="text-muted">Source : {{ article.source.name}}</small></p> --> {% endcomment %}
                  <p class="card-text"><small class="text-muted">Published date and time : {{ article.publishedAt|format_my_date_string }}</small></p>
                  <p class="card-text">{{ article.content}}</p>
                </div>
              </div>
              <div class="col-md-3 d-flex justify-content-center col-sm-pull-9">
                    <img src="{{ article.urlToImage }}" class="img-thumbnail " alt="Image">
                
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div class="infinite-container">
          {% for article_map in articles_info_map.articles %}
          <div class="infinite-item">
            <div class="row">
              <div class="card mb-3 border-0 shadow-sm" style="box-shadow: 0 0 2px 2px grey; width:100%;">
                <div class="row no-gutters">
                  <div class="col-md-3 col-sm-pull-9 order-md-2">
                    {% if article_map.article_obj.urlToImage %}
                    <img src="{{ article_map.article_obj.urlToImage }}" class="borders-0 card-img-top px-3 pb-4 my-1" alt="Image">
                    {% else %}
                      {% if article_map.alternate_img %}
                        {% with article_map.alternate_img as image_static %}
                        <img src="{{image_static}}" class="borders-0 card-img-top px-3 pb-4 my-1" alt="Image">
                        {% endwith %}
                      {% endif %}
                    {% endif %}
                  </div>
                  <div class="col-md-9 col-sm-push-3  order-md-1">
                    <div class="card-body">
                      {% comment %} {% for article_topic in article_topics  %}
                      
                        <a href="{% url 'news:get_everything_by_query' %}?query={{article_topic.name|urlencode}}">
                          <h5 class="font-weight-bold d-inline text-capitalize" style="color: #ef073e;">
                            {{ article_topic }} {% if forloop.last %}{% else %}|{% endif %}
                          </h5>
                        </a>
                      
                      {% endfor %} {% endcomment %}

                      {% for article_topic in article_map.related_topics  %}
                      <a href="{% url 'experiments:get_everything_by_query' %}?query={{article_topic|urlencode}}"
                      class="">
                          <h6 class="font-weight-bold d-inline text-uppercase" 
                          style="color: #ef073e;"
                          >
                          {{ article_topic }} {% if forloop.last %}{% else %}|{% endif %}</h6>
                        </a>
                      {% endfor %}
                      <a target="__blank" href="{{ article_map.article_obj.url }}" class="">
                        <h5 class="card-title font-weight-bold" style="color: #404145;" >{{ article_map.article_obj.title }}</h5>
                      </a>
                      {% comment %} <!-- <p class="card-text d-inline">Article by : {{ article.author }}</p> --> {% endcomment %}
                      {% if article_map.article_obj.source and article_map.article_obj.source.name %}
                        <p class="card-text d-inline"><small class="text-muted">{{ article_map.article_obj.source.name}}&nbsp;&nbsp;&nbsp;&nbsp; {{ article_map.article_obj.publishedAt|format_my_date_string }}</small></p>
                      {% else %}
                        {% if article_map.alternate_source %}
                          <p class="card-text d-inline"><small class="text-muted">{{ article_map.alternate_source}}&nbsp;&nbsp;&nbsp;&nbsp; {{ article_map.article_obj.publishedAt|format_my_date_string }}</small></p>
                        {% endif %}
                      {% endif %}
                      {% comment %} <p class="card-text"><small class="text-muted">Published date and time : </small></p> {% endcomment %}
                      <div class="mb-2" >
                        <!-- <div class="collapse" id="collapseContent{{forloop.counter0}}">
                          
                            <p class="card-text" style="color: #0c0c0c;">{{ article_map.article_obj.description}}</p>

                            <a target="__blank" href="{{ article_map.article_obj.url }}" class="">
                              <p class="font-weight-bolder card-text text-primary" 
                              {% comment %} style="color: #254dfd;" {% endcomment %}
                              >Read Full Article</p></a>
                        </div> -->

                        <!-- <a class="contentCollapsed text-secondary" role="button" data-toggle="collapse" href="#collapseContent{{forloop.counter0}}" 
                        aria-expanded="false" aria-controls="collapseContent{{forloop.counter0}}">more</a> -->

                        <a class="text-secondary" target="__blank" href="{{ article_map.article_obj.url }}">more</a>

                      </div>
                      
                        <div class="d-flex justify-content-left">
                          <a class="dv-collapse">
                            <img class="img-fluid" src="{% static 'images/news/share_logo.png' %}" alt="Share" style="height:20px;" /> 
                          </a>
                          
                            <div class="ml-1 dv-collapse-next" >
                              <div class="">
                                <a class="social-share-mobile-only ml-1" href="whatsapp://send?text={{article_map.article_obj.url}}%0a%0aKeep updated on '{{article_map.related_topics.0|upper}}' at {{request.get_host}}/follow/{{article_map.related_topics.0|replace_space_with_plus}}" data-action="share/whatsapp/share">
                                <img class="img-fluid" src="{% static 'images/news/whatsapp_logo_resized.png' %}" alt="Share" style="height:20px;" /></a>
    
                                <a class="ml-1" href="https://twitter.com/intent/tweet?text={{article_map.article_obj.url}}%0a%0aKeep updated with '{{article_map.related_topics.0|upper}}' at {{request.get_host}}/follow/{{article_map.related_topics.0|replace_space_with_plus}}" class="twitter-share-button" data-show-count="false">
                                <img class="img-fluid" src="{% static 'images/news/twitter_logo.png' %}" alt="Tweet" style="height:20px;" /></a>
                              </div>
                            </div>
                          
                        </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        <div class="loading" style="display: none;">
          <div class="d-flex justify-content-center mt-2">
            <div class="spinner-border text-success text-center" role="status" style="width: 3rem; height: 3rem;">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
        </div>

        {% if articles_info_list.has_next %}
          {% if "get_everything_by_query" in url %}
            <a class="infinite-more-link" href="{% url 'experiments:get_everything_by_query' %}?page={{ articles_info_list.next_page_number|urlencode }}&query={{searched_query|urlencode}}">More</a>
          {% else %}
            {% if "topic_feed" in url %}
              <a class="infinite-more-link" href="{% url 'experiments:topic_feed' %}?page={{ articles_info_list.next_page_number|urlencode }}">More</a>
            {% elif "get_topic_by_query" in url %}
              <a class="infinite-more-link" href="{% url 'news:get_topic_by_query' searched_query|urlencode %}?page={{ articles_info_list.next_page_number|urlencode }}">More</a>
            {% endif %}
          {% endif %}
        {% endif %}


      {% endif %}

    </div>
  </div>
</div>

{% endif %}
<script type="text/javascript">
  $(window).on('load',function(e){
      $.ajax({
          url: "{{redirect_url}}",
          success: function(data){
              $('#success').html(data);
              $('#loading').remove();
          },
          error: function(){
            alert("Error. Please reload");
          }
      });
    });

  
</script>

<script src="{% static 'js/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/waypoints/infinite.min.js' %}"></script>
<script src="{% static 'js/news/news_home.js' %}" async defer></script>
{% endblock content_body %}